# Generated by Django 4.2.13 on 2026-04-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='asin',
            new_name='products_as_tier_0c4696_idx',
            old_name='products_as_tier_bc3d9d_idx',
        ),
        migrations.RenameIndex(
            model_name='bsrsnapshot',
            new_name='products_bs_asin_id_a2a354_idx',
            old_name='products_bs_asin_id_5b1c64_idx',
        ),
        migrations.AddField(
            model_name='reviewanalysis',
            name='sentiment_summary',
            field=models.TextField(blank=True, help_text='Prose summary of customer feedback', null=True),
        ),
        migrations.AlterField(
            model_name='asin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='asin',
            name='query_count',
            field=models.PositiveIntegerField(default=0, help_text='Cumulative user queries; drives tier promotion'),
        ),
        migrations.AlterField(
            model_name='bsrsnapshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='revenueestimate',
            name='confidence',
            field=models.FloatField(help_text='Model confidence score 0–1'),
        ),
        migrations.AlterField(
            model_name='revenueestimate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='revenueestimate',
            name='yoy_change_pct',
            field=models.FloatField(blank=True, help_text='Year-over-year % change', null=True),
        ),
        migrations.AlterField(
            model_name='reviewanalysis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reviewanalysis',
            name='negative_themes',
            field=models.JSONField(default=list, help_text='Top negative keywords/phrases'),
        ),
        migrations.AlterField(
            model_name='reviewanalysis',
            name='positive_themes',
            field=models.JSONField(default=list, help_text='Top positive keywords/phrases'),
        ),
        migrations.AlterField(
            model_name='reviewanalysis',
            name='sentiment_score',
            field=models.FloatField(help_text='Aggregate sentiment 1–5'),
        ),
    ]
